<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SmartExpenseTracker.Store</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartExpenseTracker.Common\SmartExpenseTracker.Common.csproj" />
    <ProjectReference Include="..\SmartExpenseTracker.Data\SmartExpenseTracker.Data.csproj" />
  </ItemGroup>

</Project>
